"""add unique product code

Revision ID: b858facc4a3a
Revises: 569b64e91c0e
Create Date: 2026-09-09 13:40:32.336567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b858facc4a3a'
down_revision = '569b64e91c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_products_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_code'))
        batch_op.drop_column('code')

    # ### end Alembic commands ###
